# Generated by Django 4.1.1 on 2023-05-31 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Wallet name')),
                ('usdt_ecr', models.CharField(blank=True, max_length=100, verbose_name='USDT_Eth Wallet')),
                ('usdt_trc', models.CharField(blank=True, max_length=100, verbose_name='USDT_TRON Wallet')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Transaction ID')),
                ('wallet', models.CharField(choices=[('None', 'Select a USDT Network'), ('USDT (ERC20)', 'USDT (ERC20)'), ('USDT (TRC20)', 'USDT (TRC20)')], max_length=200, verbose_name='Wallet ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('pending', models.BooleanField(default=True, verbose_name='Pending Transactions')),
                ('rejected', models.BooleanField(default=False, verbose_name='Rejected/Canceled Transactions')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users_info')),
            ],
        ),
    ]
