# Generated by Django 4.1.1 on 2023-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_deposit', models.IntegerField(verbose_name='Minimum Deposit')),
                ('maximum_deposit', models.IntegerField(verbose_name='Maximum Deposit')),
                ('minimum_withdraw', models.IntegerField(verbose_name='Minimum Withdraw')),
                ('maximum_withdraw', models.IntegerField(verbose_name='Minimum Withdraw')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
